### ISSUE TITLE
Pass Tap Settings to home assistant

### ISSUE THREAD

**Issue by wookienow** [mp-se/kegmon#39]
t's good to have the remaining amount and glasses in Home assistant but it would be also good to pass through the current configured data for the tap
Keg Size
Empty Keg Weight
Glass Size.

This would allow percentage calculations to be done to show % remaining as well as show a different image based on keg size.

As an alternate passing through % remaining in the keg based on the keg config would also work along with glasses and remaining.

 
This email and any attachments are confidential and must not be disclosed to any person other than the intended recipient.

**Comment by mp-se** [comment]
Good idea, i will see how to best implement that.

**Comment by mp-se** [comment]
I suggest that keg volume and glass volume are added as attributes to the volume data.

Currently the volume in (liters) is the state and { "glasses": 1 } is the attribute. If I extend the attribute to contain { "glass_volume": 1, "keg_volume": 1 } both in liters you can do the calculation. I can also add "keg_percentage": 1 as an attribute so you dont need to calculate that. 

Dont really understand why you need the keg weight since this is not really usable ?

**Comment by mp-se** [comment]
You can try the build in the dev branch, it should have the requested params. This is an example from my install:

{"glasses":31.2,"keg_volume":19.00,"glass_volume":0.40,"keg_percent":65.59}
